require: rubocop

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec/**/*

Style/Documentation:
  Enabled: false